### ISSUE TITLE
How to check the Semantic ID of movies in ml-1m after training?

### ISSUE THREAD

**Issue by xy-lin77** [EdoardoBotta/RQ-VAE-Recommender#10]
Could you please briefly explain how to visualize the semantic IDs generated by RQ-VAE? It appears that I can train the RQ-VAE, but I cannot find any explicit output. For example, the semantic id of movie xxx is <a_12><b_34><c_56><d_1>.

Thanks a lot.

**Comment by xy-lin77** [comment]
I have forked this repo and I have updated the training and inference script of rqvae for your reference

**Comment by EdoardoBotta** [comment]
Sounds good. I am plannning to make the SemanticIdTokenizer able to load a pretrained RQ-VAE. This will make inference from the RQ-VAE doable from the SemanticIdTokenizer class itself, by using the existing precompute_corpus_ids method.
